---
version: 2
plan:
  project-key: BUG
  key: PL
  name: PL
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  tasks:
  - script:
      interpreter: SHELL
      scripts:
      - for i in {0..10}; do sleep 1; echo $i; done; echo "done";
  other:
    all-other-apps:
      custom.test.ephemeral.agent.enabled: 'false'
  artifact-subscriptions: []
repositories: []
# Remove line above if want to set repository with YAML file as primary repository of plan
triggers: []
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: BUG-PL
plan-permissions:
  - users:
      - admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
      - view-configuration
...
